#include "Menu.h"

int main()
{
	Menu m;
	//m.menuSumNum();
	//m.menuAddDigits();
	//m.menuFirstUniqChar();
	//m.menuMinimumNumberGame();
	//m.menuPangramSentence();
	//m.menuMaximumNumberInSentences();
	//m.menuCountDivideDigits();
	//m.menuDifferenceOfSums();
	//m.menuFindWordsContaining();
	//m.menuMaximumWealth();
	//m.menuToLowerCase();
	//m.menuEmployeesWhoMetTarget();
	//m.menuXorOperation();
	//m.menuSubtractProductAndSum();
	//m.menuSumOfMultiples();
	//m.menuFirstPalindrome();
	//m.menuDifferenceOfSum();
	//m.menuFirstUniqChar();
	//m.menuCanAliceWin();
	//m.menuJudgeCircle();
	//m.menuCountKeyChanges();
	//m.menuArraySign();
	//m.menuThreeConsecutiveOdds();
	//m.menuSortedSquares();
	//m.menuCalPoints();
	//m.menuTriangleType();
	//m.menuIsValidParentheses();
	//m.menuRomanToInt();
	//m.menuLongestCommonPrefix();
	//m.menuPlusOne();
	//m.menuDeleteDuplicatesListNode();
	//m.menuMergeTwoLists();
	//m.menuCanPlaceFlowers();
	//m.menuKidsWithCandies();
	//m.menuProductExceptSelf();
	//m.menuReverseVowels();
	//m.menuClimbStairs();
	//m.menuReverseWords();
	//m.menuIsUgly();
	//m.menuPascalsTriangle();
	//m.menuMajorityElement();
	//m.menuMajorityElementII();
	//m.menuRepeatedNTimes();
	//m.menuIsPathCrossing();
	//m.menuIsPrefixOfWord();
	//m.menuFindEvenNumbers();
	//m.menuFindWords();
	//m.menuReverseString();
	//m.menuTwoSum();
	//m.menuIsSubsequence();
	//m.menuDiStringMatch();
	//m.menuSortArrayByParityII();
	//m.menuSortArrayByParity();
	//m.menuFindIndices();
	//m.menuCountPairs();
	//m.menuMakeSmallestPalindrome();
	//m.menuMergeArrays();
	//m.menuGetCommon();
	//m.menuContainsNearbyDuplicate();
	//m.menuFindLHS();
	//m.menuFindMaxAverage();
	//m.menuDecrypt();
	//m.menuRotate();
	//m.menuCountGoodSubstrings();
	//m.menuBuildArray();
	//m.menuMinimumOperations();
	//m.menuRecoverOrder();
	//m.menuGetConcatenation();
	//m.menuConvertTemperature();
	//m.menuMinOperations();
	//m.menuDefangIPaddr(); 
	//m.menuGetSneakyNumbers();
	//m.menuIsStrictlyPalindromic();
	//m.menuPivotArray();
	//m.menuNumIdenticalPairs();
	//m.menuMergeNodes();
	//m.menuInsertGreatestCommonDivisors();
	//m.menuMergeInBetween();
	//m.menuGetDecimalValue();
	//m.menuSpiralMatrixIV();
	//m.menuPairSum();
	//m.menuMiddleNode();
	//m.menuMinOperations();
	//m.menuScoreOfString();
	//m.menuMaxDistinct();
	//m.menuTransformArray();
	//m.menuNumJewelsInStones();
	//m.menuAlternatingSum();
	//m.menuReversePrefix();
	//m.menuShuffleArray();
	//m.menuFindClosestPerson();
	//m.menuMaxFreqSum();
	//m.menuMinBitFlips();
	//m.menuLeftRightDifference();
	//m.menuSum();
	//m.menuInterpret();
	//m.menuValidStrings();
	//m.menuSmallestEvenMultiple();
	//m.menuReverseDegree();
	//m.menuCountConsistentStrings();
	m.menuConvertDateToBinary();
}

//3146. Permutation Difference between Two Strings
//1282. Group the People Given the Group Size They Belong To
//1365. How Many Numbers Are Smaller Than the Current Number
//2037. Minimum Number of Moves to Seat Everyone
//1221. Split a String in Balanced Strings